# The URL the site will be built for
base_url = "https://zackerthescar.com"

# The site title and description; used in feeds by default.
title = "r/c/s"
description = "r/c/s streams of thought"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Tags
taxonomies = [
    {name = "tags"}
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "boron"

[extra]
# Put all your custom variables here

# Enable Unicode fonts
use_full_hack_font = true

# Site details
logo_text = "r/c/s"
author = "r/c/s"

# Menu items
menu_items = [
    {name = "home", url = "$BASE_URL", color = "caithe"},
    {name = "about me", url = "$BASE_URL/about", color = "tayne" },
    {name = "blog", url = "$BASE_URL/blog", color = "naia"},
    {name = "csci8980-pfpl", url = "$BASE_URL/csci8980-s25", color = "komi" },
    {name = "resume", url = "$BASE_URL/docs/resume_shaunloo.pdf", color = "yasmi" },
    {name = "links", url = "$BASE_URL/links", color = "wikitori" },
    {name = "GitHub", url = "https://github.com/zackerthescar", newtab = true, color = "watchdog" },
]

# "Listening to" widget in the left, would be nice if
# we could automate this by pulling some bandcamp thing
listening_to = { artist = "bit depth", release = "herdbound",link = "https://bitdepth.bandcamp.com/album/herdbound", img = "https://f4.bcbits.com/img/a1269997044_10.jpg"}

# 88x31s
88x31 = [
    {name = "macos", img = "macos.gif", url = "https://apple.com/macos"},
    {name = "debian", img = "debian.gif", url = "https://www.debian.org/"},
    {name = "ffmpeg", img = "ffmpeg.gif", url = "https://ffmpeg.org/"},
    {name = "firefox", img = "firefox4.gif", url = "https://mozilla.com/firefox/"},
    {name = "csh", img = "csh.gif", url = "https://carseatheadrest.bandcamp.com/album/twin-fantasy"},
    {name = "wii", img = "wii.gif", url = "#"},
    {name = "color", img = "color.png", url = "#"},
    {name = "xp", img = "xp.gif", url = "#"},
    {name = "xenia", img = "xeniatrans_now.gif", url = "#"},
    {name = "rainbow", img = "rainbow.gif", url = "https://thetrevorproject.org/"},
    {name = "bi", img = "bi.png", url = "#"},
    {name = "trans", img = "trans.png", url = "#"},
    {name = "enby", img = "enby.png", url = "#"},
    {name = "dolby", img = "dolby_digital.gif", url = "#"},
    {name = "web3", img = "web3.gif", url = "#"},
    {name = "mt32", img = "mt32now.gif", url = "#"}
]

webrings = [
    { name = "Twitching Whiskers", onclick="weblineWarp();", img="/img/train.png"},
    { name = "Nix", next="https://nixwebr.ing/next/zackerthescar", prev="https://nixwebr.ing/prev/zackerthescar", rand="https://nixwebr.ing/rand", img="/img/NixOS_logo.svg"}
]

page_titles = "combined"
